---
name: Elliot Gould
position: "PhD Candidate, Research Assistant"
address: "School of BioSciences, University of Melbourne"
phone: 0406680382
email: "elliot.gould@unimelb.edu.au"
github: egouldo
aboutme: "Elliot Gould is a PhD candidate at the School of BioSciences, and a Quantitative Research Assistant on the [repliCATS project](replicats.research.unimelb.edu.au/) at the School of BioSciences, University of Melbourne. Their PhD investigates the transparency and reproducibility of ecological models in applied ecology and conservation decision-making. In their role as a Quantitative Research Assistant, Elliot has managed a small team of researchers to develop a data provisioning platform for the repliCATS project, and taken lead responsibility for data management, as well as contributing to research on metascience. They have an enthusiasm for teaching and skill-sharing, particularly with regard to building a strong community of practice in emerging open-science methodology and computational biology within ecology and conservation. Elliot has co-designed a learning and assessment module for the subject Vegetation Management and Conservation that aimed to teach recent developments in open-science practice whilst improving subject-specific learning outcomes. Elliot’s primary research interest is in building ecological models for aiding ecological management and conservation decisions. Other research interests include decision-theory, Structured Decision Making, plant ecology (especially grasslands of the Victorian Volcanic Plains), data visualisation and building new tools for open-science."
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(vitae)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ dates, ~ details,
    "Doctor of Philosophy, Science", "University of Melbourne", "November 2017 - August 2023 (expected)", "Thesis Title: Reproducibility and Transparency of Ecological Models in Applied Ecology and Conservation Science",
    "Master of Science (Distinction)", "University of Melbourne", "March 2012 - December 2015", "Research Training Degree, with 70% original research and 30% coursework. Course Weighted Average Mark: 82.312",
  "Master of Science (Distinction)", "University of Melbourne", "March 2012 - December 2015", "Thesis Title: Managing Grasslands with Models: Resolving uncertainty and allocating effort among a suite of sites.",
    "Bachelor of Science", "University of Melbourne", "March 2005 - November 2011", "Major in Ecology, First Class Honours Average",
  "Bachelor of Arts", "University of Melbourne", "March 2005 - November 2011", "Major in Indonesian, First Class Honours Average"
) %>% 
  detailed_entries(what = uni,when =  dates, with = degree,why =  details) 
```

# Employment History

```{r employment}
tribble(
  ~ what, ~ when, ~ with, ~ where, ~why,
  "School of Historical and Philosophical Studies, School of BioSciences", "February 2019 - Present", "Quantitative Research Assistant - repliCATS, SCORE Program", "University of Melbourne", "Systematising Confidence in Open Research and Evidence (SCORE) is a Research Program initiated by the Defense Advanced Research Projects Agency  (DARPA) that aims to develop and deploy automated tools to assign 'confidence scores' to Social and Behavioural research results and claims in light of recent evidence about the 'Replication Crisis' besetting Science. The repliCATS project is one team within the SCORE project, based in Melbourne. In this role, Elliot lead a small team within the repliCATS project to build data analysis software and infrastructure to manage and deliver data products to internal teams and external partners. Research components of the role include modelling to investigate predictors of replication success.",
  "School of BioSciences", "2012 - 2020", "Demonstrator / Tutor", "University of Melbourne", "Vegetation Management and Conservation, 2018, 2019. In addition to demonstrating, I co-developed a teaching and learning module, and developed and delivered a workshop teaching the basics of data-science in R using data collected by the students.",
    "School of BioSciences", "2012 - 2020", "Demonstrator / Tutor", "University of Melbourne", "Environmental Risk Assessment: 2016, 2017, 2018.",
  "School of BioSciences", "2012 - 2020", "Demonstrator / Tutor", "University of Melbourne", "Applied Ecology: 2014, 2015.",
    "School of BioSciences", "2012 - 2020", "Demonstrator / Tutor", "University of Melbourne", "Ecology: 2014.",
  "School of BioSciences", "2012 - 2020", "Demonstrator / Tutor", "University of Melbourne", "Biology of Cells and Organisms: 2012, 2013, 2014, 2015.",
   "School of BioSciences", "August 2015 - Present", "Research Assistant", "University of Melbourne", "National Environmental Science Programme, Threatened Species Recovery Hub: Conservation actions for Threatened Ecological Communities.",
    "School of BioSciences", "August 2015 - Present", "Research Assistant", "University of Melbourne", "Various plant ecology and Structured Decision Making projects, involving: data analysis and visualisations, building shiny Apps, model building and testing.",
  "School of Geography", "August 2015 - January 2017", "Research Assistant", "University of Melbourne", "Modelling Drinking Water Availability in the Yangtze River Estuary with Bayesian Belief Networks.",
) %>% 
  detailed_entries(what, when, with, where, why)
```

# Scholarships and Awards

```{r scholarships}
tribble(~Award, ~Description, ~Organisation, ~Year,
        "Australian Government Research Training Program (RTP) Scholarship", "Awarded to high-achieving students undertaking graduate research at the University of Melbourne.", "The University of Melbourne", "2017 - Current",
        "G.A.M. Scott Research Award", "Supports a graduate research student, or an honours or equivalent student, in the discipline of botany, within the School of BioSciences undertaking research that involves field work in the areas of either bryophytes or plant ecology.", "School of Botany Foundation, The University of Melbourne", "2012",
        "Muriel Ramm Science Bursary", "Awarded to a student entering honours or a postgraduate degree in the Faculty of Science. It goes to the candidate judged most likely to benefit academically from it, taking into account financial need or hardship.", "Faculty of Science, The University of Melbourne", "2012",
        "Graduate Access Bursary", "Awarded to graduate coursework students who have experienced difficult circumstances that impacted on their tertiary studies.", "Melbourne Scholarships, The University of Melbourne", "2012",
        "Commonwealth Education Costs Scholarship", "Commonwealth Scholarships were established to increase higher education participation by students from low socio-economic backgrounds and from rural and regional areas.", "Commonwealth Government of Australia", "2006 - 2010"
        ) %>% 
        detailed_entries(why = Description, when = Year, with = Award, what = Organisation)
```

# Talks and Workshops

```{r talks}
tibble::tribble(
  ~name, ~event, ~location, ~year,
  "Workshop: 'Preregistration Templates for Model-Based Research' ", "Model Based Research and Reproducibility Workshop", "Centre for Open Science, Virgina, USA", 2020,
  "Workshop: 'Preregistration Templates for Ecology and Conservation'", "Department of Land Water & Planning", "Melbourne", 2020,
  "Workshop: 'Transparency & Reproducibility in Non-Hypothesis Testing Research' ", "Society for the Improvement of Psychological Sciences", "Rotterdam", 2019,
    "Poster Presentation: 'Questionable Research Practices in Non-Hypothesis Testing Research' ", "MetaScience Symposium & Association for Interdisciplinary Meta-Research and Open Science Conference", "San Francisco & Melbourne", 2019,
  "Talk: 'Choose your own adventure: Researcher degrees of freedom and Questionable Research Practices in ecological modelling for decision support' ", "Quantitative and Applied Ecology Group", "Melbourne", 2018, 
  "Talk: 'Questionable Research Practices in Non-Hypothesis Testing Research' ", "Credibility Revolution 2018", "Melbourne", 2018,
  "Talk 'Beyond P-hacking: Questionable Research Practices in Non-Null Hypothesis Significance Testing' ", "UQ Open Science Conference", "Brisbane", 2018,
"Talk 'Questionable Research Practices in Ecology and Conservation' ", "Quantitative and Applied Ecology Group Annual Retreat", "Melbourne", 2018,
"Workshop: 'Data Wrangling for Ecologists'", "Victorian Biodiversity Conference", "Melbourne", 2017
) %>% 
  detailed_entries(
    what = name,
    when = year,
    with = event,
    where = location
  )


```

# Research Consultancy, Professional Membership

```{r}
tibble::tribble(
  ~name, ~year, ~with, ~location, ~description,
  "Testing and Developing preregistration templates for ecology and conservation using a case study of environmental flows management in Victoria, Australia", "March 2020 - Present", "Department of Environment Land Water & Planning", "Consultancy", "This research consultancy contributes to Elliot's PhD. This work involved the design and delivery of a collaborative workshop with DELWP in order to develop preregistration templates and methodology relevant to ecological modelling, in particular within decision-making and applied contexts.",
  "Secretary / Treasurer, www.sortee.org","September 2020 - Present", "Society for Open, Reliable, and Transparent Ecology and Evolutionary Biology (SORTEE)", "Professional Membership", "SORTEE is a service organization which brings together researchers working to improve reliability and transparency through cultural and institutional changes in ecology, evolutionary biology, and related fields broadly defined. Anyone interested in improving research in these disciplines is welcome to join, regardless of experience. The society is international in scope, membership, and objectives. Elliot is a founding member and co-chair of the executive committee."
) %>% detailed_entries(
  what = name,
  when = year,
  with = with,
  where = location,
  why = description
)
```
