---
name: Elliot Gould
position: "PhD Candidate, Research Assistant, Consultant"
address: "School of Agriculture, Food and Ecosystem Sciences, University of Melbourne"
phone: '+61406680382'
email: "elliot.gould@unimelb.edu.au"
github: egouldo
aboutme: "Elliot Gould is a PhD candidate at the School of Agriculture, Food and Ecosystem Sciences, and a Quantitative Research Assistant on the [repliCATS project](replicats.research.unimelb.edu.au/) at the School of History and Philosophical Studies, University of Melbourne. Their PhD investigates the transparency and reproducibility of ecological models in applied ecology and conservation decision-making. In their role as a Quantitative Research Assistant, Elliot managed a small team of researchers to develop a data analytics and management platform for the repliCATS project, and contributed to research on metascience. They have an enthusiasm for teaching and skill-sharing, particularly with regard to building a strong community of practice in emerging open-science methodology and computational biology within ecology and conservation. Elliot's research seeks to use data science techniques to advance the open-science movement by improving transparency and reproducibility, focussing on ecology and conservation Science. Other research interests include decision-theory, Structured Decision Making, and plant ecology (especially grasslands of the Victorian Volcanic Plains)."
date: "`r format(Sys.time(), '%B %Y')`"
#profilepic: "Gould_professional_profile_pic_photo.jpeg"
#orcid: 0000-0002-6585-538X
documentclass: article
classoption: a4paper
#letterpaper
output: 
  vitae::awesomecv:
    keep_tex: true
    fig_crop: no
always_allow_html: yes
params:
  work_dir:
    value: x
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(vitae)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ dates, ~ details,
    "Doctor of Philosophy, Science", "University of Melbourne", "November 2017 - Present", "Thesis Title: Reproducibility and Transparency of Ecological Models in Applied Ecology and Conservation Science",
    "Master of Science (Distinction)", "University of Melbourne", "March 2012 - December 2015", "Research Training Degree, with 70% original research and 30% coursework. Course Weighted Average Mark: 82.312",
  "Master of Science (Distinction)", "University of Melbourne", "March 2012 - December 2015", "Thesis Title: Managing Grasslands with Models: Resolving uncertainty and allocating effort among a suite of sites.",
    "Bachelor of Science", "University of Melbourne", "March 2005 - November 2011", "Major in Ecology, First Class Honours Average",
  "Bachelor of Arts", "University of Melbourne", "March 2005 - November 2011", "Major in Indonesian, First Class Honours Average"
) %>% 
  detailed_entries(what = uni,when =  dates, with = degree,why =  details) 
```

# Employment History

```{r employment}
tribble(
  ~ what, ~ when, ~ with, ~ where, ~why,
  "School of Historical and Philosophical Studies, School of BioSciences", "February 2019 - Present", "Quantitative Research Assistant - repliCATS, SCORE Program", "University of Melbourne", "Systematising Confidence in Open Research and Evidence (SCORE) is a Research Program initiated by the Defense Advanced Research Projects Agency  (DARPA) that aims to develop and deploy automated tools to assign 'confidence scores' to Social and Behavioural research results and claims in light of recent evidence about the 'Replication Crisis' besetting Science. The repliCATS project is one team within the SCORE project, based in Melbourne. In this role, Elliot lead a small team within the repliCATS project to build data analysis software and infrastructure to manage and deliver data products to internal teams and external partners. Research components of the role include modelling to investigate predictors of replication success.",
    "School of BioSciences", "2012 - Present", "Demonstrator / Tutor", "University of Melbourne", "Environmental Risk Assessment: 2016, 2017, 2018, 2022, 2023",
   "School of BioSciences", "2012 - Present", "Demonstrator / Tutor", "University of Melbourne", "Guest lectures in 'Biometry' (2023) and 'Critical Thinking with Data' (2021).",
    "School of BioSciences", "2012 - Present", "Demonstrator / Tutor", "University of Melbourne", "Vegetation Management and Conservation, 2018, 2019. In addition to demonstrating, I co-developed a teaching and learning module, and developed and delivered a workshop teaching the basics of data-science in R using data collected by the students.",
  "School of BioSciences", "2012 - Present", "Demonstrator / Tutor", "University of Melbourne", "Applied Ecology: 2014, 2015.",
    "School of BioSciences", "2012 - Present", "Demonstrator / Tutor", "University of Melbourne", "Ecology: 2014.",
  "School of BioSciences", "2012 - Present", "Demonstrator / Tutor", "University of Melbourne", "Biology of Cells and Organisms: 2012, 2013, 2014, 2015.",
   "School of BioScience, School of Geography", "2015 - Present", "Research Assistant, Various Roles", "University of Melbourne", "National Environmental Science Programme, Threatened Species Recovery Hub: Conservation actions for Threatened Ecological Communities.",
    "School of BioScience, School of Geography", "2015 - 2019", "Research Assistant, Various Roles", "University of Melbourne", "Various plant ecology and Structured Decision Making projects, involving: data analysis and visualisations, building shiny Apps, model building and testing."
) %>% 
  detailed_entries(what, when, with, where, why)
```

# Scholarships and Awards

```{r scholarships}
tribble(~Award, ~Description, ~Organisation, ~Year,
        "Science Abroad Travelling Scholarships, 2023", "This scholarship supports PhD students in the Faculty of Science undertaking travel to attend conferences, fieldwork, etc. as part of a Study Away request. Awarded $2000.", "University of Melbourne, Faculty of Science, School of Ecosystem and Forest Sciences", "2023",
        "Metascience 2023 travel award", "$300 USD travel award to attend the Metascience 2023 conference in Washington, D.C", "Metascience Conference", "2023",
        "AIMOS top-up scholarship", "AIMOS will award up to four top-up scholarships per year to PhD or Masters students working on a meta-research project.", "Association for Interdisciplinary Metaresearch and Open Science (AIMOS)", "2022",
        "Research Excellence Award for Interdisciplinary Research (Group Award)", "Nominees will have been collaborators in interdisciplinary research of outstanding influence, that is, the establishment of new, or advancing of existing, collaborations and programs that draw on multiple disciplines typically involving multiple faculties or schools.", "University of Melbourne", "2022",
        "Melbourne Centre of Data Science Doctral Academy Fellow", "The MCDS Doctoral Academy aims to bring together a campus wide multi-disciplinary cohort of PhD students (MCDS Doctoral Academy Fellows) to share their research, domain challenges and thoughts around the use, implementation and application of data science in their fields.", "Melbourne Centre for Data Science, University of Melbourne", "2021",
        "Australian Government Research Training Program (RTP) Scholarship", "Awarded to high-achieving students undertaking graduate research at the University of Melbourne.", "The University of Melbourne", "2017 - Current",
        ) %>% 
        detailed_entries(why = Description, when = Year, with = Award, what = Organisation)
```

# Publications

```{r pubs}
tribble(~title, ~year, ~author, ~journal, ~doi,
        "Same data, different analysts: variation in effect sizes due to analytical decisions in ecology and evolutionary biology", "2023", "Gould, E., Fraser, H., Parker, T.H. et al.", "EcoEvoRxiv", "https://doi.org/10.32942/X2GG62",
        "Implementing code review in the scientific workflow: Insights from ecology and evolutionary biology", "2023", "Ivimey-Cook, E., Pick, J.L., Bairos-Novak, K., Culina, A., Gould, E., Grainger, M., Marshall, B., Moreau, D., Paquet, M., Royauté, R., Sanchez-Tojar, A., Silva, I., Windecker, S.", "Journal of Evolutionary Biology", "https://doi.org/10.1111/jeb.14230",
        "Predicting reliability through structured expert elicitation with the repliCATS (Collaborative Assessments for Trustworthy Science) process", "2023","Fraser, H.,Bush, M., Wintle, B.C., Mody, F., Smith, E.T.,Hanea, A.M., Gould, E.,  Hemming, V., Hamilton, D.G., Rumpff, L., Wilkinson, D.P., Pearson, R., Singleton Thorn, F., Ashton, R., Willcox, A., Gray, C.T., Head, A., Ross, M., Groenewegen, R., Marcoci, A., Vercammen, A., Parker, T.H., Hoekstra, R., Nakagawa, S., Mandel, D.R., van Ravenzwaaij, D., McBride, M.F., Sinnott, R.O., Vesk, P.A., Burgman, M., Fidler, F.", "PLOS ONE", "https://doi.org/10.1371/journal.pone.0274429",
        "Method Reporting with Initials for Transparency (MeRIT) promotes more granularity and accountability for author contributions", "2023",  "Nakagawa, S., Ivimey-Cook, E., Grainger, M.J., O’Dea, R.E., Burke, S., Drobniak, S.M., Gould, E., Macartney, E.L., Martinig, A.R., Paquet, M., Morrison, K., Pick, J.L., Pottier, P., Ricolfi, L., Wilkinson, D.P., Willcox, A., Williams, C., Wilson, L.A.B., Windecker, S.M., Yang, Y., Lagisz, M.", "Nature Communications", "https://doi.org/10.1038/s41467-023-37039-1",
        "Predicting and reasoning about replicability using structured groups", "2023",  "Wintle, B.C., Mody, F., Smith, E.T.,Hanea, A.M., Wilkinson, D.P., Hemming, V., Bush, M., Fraser, H., Singleton Thorn, F., McBride, M.F., Gould, E., Head, A., Hamilton, D.G., Rumpff, L., Hoekstra, R., Fidler, F.", "Royal Society Open Science", "https://osf.io/preprints/metaarxiv/vtpmb/",
        "What state of the world are we in? Targeted monitoring to detect transitions in vegetation restoration projects", "2022", "Jones, C.S., Thomas, F.M., Michael, D.R., Fraser, H., Gould, E., Begley, J., Wilson, J., Vesk, P.A., Rumpff, L.", "Ecological Applications", "https://doi.org/10.1002/eap.2728",
        "Mathematically aggregating experts’ predictions of possible futures", "2021",  "Hanea, A.M., Wilkinson, D.P., McBride, M.F., Lyon, A., van Ravenzwaaij, D., Singleton Thorn, F., Gray, C.T., Mandel, D.R., Willcox, A., Gould, E., Smith, E.T., Mody, F., Bush, M., Fidler, F., Fraser, H., Wintle, B.C.", "PLOS ONE", "https://doi.org/10.1371/journal.pone.0256919",
        "Towards open, reliable, and transparent ecology and evolutionary biology", "2021",  "O'Dea, R.E., Parker, T.H., Chee, Y.E., Culina, A., Drobniak, S.M., Duncan, D.H., Fidler, F., Gould, E., Ihle, M., Kelly, C., Lagisz, M., Roche, D.G., Sánchez-Tójar, A., Wilkinson, D.P., Wintle B.C., Nakagawa, S.", "BMC Biology", "https://doi.org/10.1186/s12915-021-01006-3",
        "A practical guide for conservation planning using the General Ecosystem Model for Southern Australian Woodlands.", "2021", "Good, M., Fraser, H., Gould, E., Vesk, P., Rumpff, L.", "NESP Threatened Sprecies Recovery Hub Project 7.2, Brisbane", "https://www.nespthreatenedspecies.edu.au/media/yvlbs1tk/7-2-a-practical-guide-for-conservation-planning-using-the-general-ecosystem-model-for-southern-australian-woodlands_v3.pdf"
) %>% 
  detailed_entries(
    what = author,
    when = year,
    with = title,
    where = journal,
    why = doi
  )
```


# Selected Talks and Workshops

```{r talks}
tibble::tribble(
  ~name, ~event, ~location, ~year,
    "Many Analysts: Heterogeneity in results among studies in ecology and evolutionary biology", "Invited speaker Mini-note Panel: Association for Interdisciplinary Metaresearch and Open Science Conference", "Melbourne, Australia", 2022,
    "A many-analyst project in ecology and evolutionary biology demonstrates heterogeneity driven by analysts’ decisions and generates new questions about variability in this heterogeneity ", "Big Team Science Conference", "Global - Online", 2022,
  "Workshop: Creating reproducible workflows in R with the targets:: package", "Society for Open Reliable and Transparent Ecology and Evoluation Workshop Series", "Online - Oceania", 2022,
  "'ResearchOps: A principled framework and guide to computational reproducibility', and 'Modelling as Ways of Knowing - How Viewing Models as an Epistemic Activity is useful in Ecology'", "Association for Interdisciplinary Metaresearch and Open Science Conference", "Melbourne, Australia", 2021,
  "Workshop: 'Preregistration Templates for Model-Based Research'", "Model Based Research and Reproducibility Workshop", "Centre for Open Science", 2020,
    "Poster Presentation: 'Questionable Research Practices in Non-Hypothesis Testing Research' ", "MetaScience Symposium & Association for Interdisciplinary Meta-Research and Open Science Conference", "San Francisco & Melbourne", 2019,
) %>% 
  detailed_entries(
    what = name,
    when = year,
    with = event,
    where = location
  )
```

# Research Consultancy, Professional Membership

```{r}
tibble::tribble(
  ~name, ~year, ~with, ~location, ~description,
  "Preregistration Template Working Group", "2023", "Center of Open Science", "Professional Membership", " the Preregistration Template Working Group is working to: 1. Establish criteria to evaluate the suitability of new preregistration templates for inclusion in the OSF. 2. Develop a procedure by which community creators of preregistration templates can put templates forward for inclusion in OSF., 3. Advise and inform COS on issues related to preregistration implementation in OSF.",
  "Testing and Developing preregistration templates for ecology and conservation using a case study of environmental flows management in Victoria, Australia", "March 2020 - Present", "Victorian Government Department of Environment Land Water & Planning", "Consultancy", "This research consultancy contributes to Elliot's PhD. This work involved the design and delivery of a collaborative workshop with DELWP in order to develop preregistration templates and methodology relevant to ecological modelling, in particular within decision-making and applied contexts.",
  "Founding Member and Secretary / Treasurer, www.sortee.org","2020 - 2022, 2023", "Society for Open, Reliable, and Transparent Ecology and Evolutionary Biology (SORTEE)", "Professional Membership", "SORTEE is a service organization which brings together researchers working to improve reliability and transparency through cultural and institutional changes in ecology, evolutionary biology, and related fields broadly defined."
) %>% detailed_entries(
  what = name,
  when = year,
  with = with,
  where = location,
  why = description
)
```
